## Convert GAF file into a CSV file

In [3]:
%pip install pandas

Requirement already satisfied: pandas in ./.venv/lib/python3.14/site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in ./.venv/lib/python3.14/site-packages (from pandas) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [3]:
import os
from pathlib import Path

# Define the input directory
input_files = 'input_files'

# Get all gaf files
gaf_files = [f for f in os.listdir(input_files) if f.endswith('.gaf')]
print(f"Found {len(gaf_files)} GAF file(s):")
for file in gaf_files:
    print(f"  - {file}")

Found 7 GAF file(s):
  - Geobacillus_thermodenitrificans_NG80_2-420246.gaf
  - Bacillus_megaterium_DSM_319-592022.gaf
  - Bacillus_subtilis_168-224308.gaf
  - Bacillus_amyloliquefaciens_FZB42-326423.gaf
  - Geobacillus_kaustophilus_HTA426-235909.gaf
  - Escherichia_coli_K-12_ecocyc_83333.gaf
  - Bacillus_licheniformis_ATCC_14580-279010.gaf

In [4]:
import pandas as pd

for gaf_file in gaf_files:
    gaf_path = Path(input_files) / gaf_file
    df = pd.read_csv(gaf_path, sep='\t', comment='!', header=None, dtype=str)
    csv_path = gaf_path.with_suffix('.csv')
    df.to_csv(csv_path, index=False)
    print(f"Converted {gaf_file} to {csv_path.name}")
    display(df.head())

Converted Geobacillus_thermodenitrificans_NG80_2-420246.gaf to Geobacillus_thermodenitrificans_NG80_2-420246.csv

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,UniProtKB,A4IJ84,dnaA,NaN,GO:0000166,GO_REF:0000037,IEA,UniProtKB-KW:KW-0547,F,Chromosomal replication initiator protein DnaA,dnaA|GTNG_0001,protein,taxon:420246,20191214,UniProt,NaN,NaN
1,UniProtKB,A4IJ84,dnaA,NaN,GO:0003677,GO_REF:0000002,IEA,InterPro:IPR001957|InterPro:IPR018312,F,Chromosomal replication initiator protein DnaA,dnaA|GTNG_0001,protein,taxon:420246,20191214,InterPro,NaN,NaN
2,UniProtKB,A4IJ84,dnaA,NaN,GO:0003677,GO_REF:0000037,IEA,UniProtKB-KW:KW-0238,F,Chromosomal replication initiator protein DnaA,dnaA|GTNG_0001,protein,taxon:420246,20191214,UniProt,NaN,NaN
3,UniProtKB,A4IJ84,dnaA,NaN,GO:0003688,GO_REF:0000002,IEA,InterPro:IPR001957|InterPro:IPR018312,F,Chromosomal replication initiator protein DnaA,dnaA|GTNG_0001,protein,taxon:420246,20191214,InterPro,NaN,NaN
4,UniProtKB,A4IJ84,dnaA,NaN,GO:0003688,GO_REF:0000104,IEA,UniRule:UR000084164,F,Chromosomal replication initiator protein DnaA,dnaA|GTNG_0001,protein,taxon:420246,20191214,UniProt,NaN,NaN

Converted Bacillus_megaterium_DSM_319-592022.gaf to Bacillus_megaterium_DSM_319-592022.csv

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,UniProtKB,D5D917,dnaA,NaN,GO:0000166,GO_REF:0000038,IEA,UniProtKB-KW:KW-0547,F,Chromosomal replication initiator protein DnaA,dnaA|BMD_0001,protein,taxon:592022,20191214,UniProt,NaN,NaN
1,UniProtKB,D5D917,dnaA,NaN,GO:0003677,GO_REF:0000002,IEA,InterPro:IPR001957|InterPro:IPR018312,F,Chromosomal replication initiator protein DnaA,dnaA|BMD_0001,protein,taxon:592022,20191214,InterPro,NaN,NaN
2,UniProtKB,D5D917,dnaA,NaN,GO:0003677,GO_REF:0000038,IEA,UniProtKB-KW:KW-0238,F,Chromosomal replication initiator protein DnaA,dnaA|BMD_0001,protein,taxon:592022,20191214,UniProt,NaN,NaN
3,UniProtKB,D5D917,dnaA,NaN,GO:0003688,GO_REF:0000002,IEA,InterPro:IPR001957|InterPro:IPR018312,F,Chromosomal replication initiator protein DnaA,dnaA|BMD_0001,protein,taxon:592022,20191214,InterPro,NaN,NaN
4,UniProtKB,D5D917,dnaA,NaN,GO:0003688,GO_REF:0000104,IEA,UniRule:UR000084164,F,Chromosomal replication initiator protein DnaA,dnaA|BMD_0001,protein,taxon:592022,20191214,UniProt,NaN,NaN

Converted Bacillus_subtilis_168-224308.gaf to Bacillus_subtilis_168-224308.csv

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,UniProtKB,A0A2K4Z9G8,cmpA,NaN,GO:0030435,GO_REF:0000037,IEA,UniProtKB-KW:KW-0749,P,Cortex morphogenetic protein A,cmpA|BSU_04785,protein,taxon:224308,20191214,UniProt,NaN,NaN
1,UniProtKB,A0A2K4Z9G8,cmpA,NaN,GO:0042763,GO_REF:0000039,IEA,UniProtKB-SubCell:SL-0119,C,Cortex morphogenetic protein A,cmpA|BSU_04785,protein,taxon:224308,20191214,UniProt,NaN,NaN
2,UniProtKB,A0A2K4Z9H7,BSU_02585,NaN,GO:0016020,GO_REF:0000038,IEA,UniProtKB-KW:KW-0472,C,Uncharacterized protein,BSU_02585,protein,taxon:224308,20191214,UniProt,NaN,NaN
3,UniProtKB,A0A2K4Z9H7,BSU_02585,NaN,GO:0016021,GO_REF:0000038,IEA,UniProtKB-KW:KW-0812,C,Uncharacterized protein,BSU_02585,protein,taxon:224308,20191214,UniProt,NaN,NaN
4,UniProtKB,A0A2K4Z9H8,BSU_17689,NaN,GO:0016020,GO_REF:0000038,IEA,UniProtKB-KW:KW-0472,C,Uncharacterized protein,BSU_17689,protein,taxon:224308,20191214,UniProt,NaN,NaN

Converted Bacillus_amyloliquefaciens_FZB42-326423.gaf to Bacillus_amyloliquefaciens_FZB42-326423.csv

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,UniProtKB,A0A0B4ZZ86,A0A0B4ZZ86,NaN,GO:0000272,GO_REF:0000038,IEA,UniProtKB-KW:KW-0624,P,"Endo-1,4-beta-xylanase",NaN,protein,taxon:326423,20191214,UniProt,NaN,NaN
1,UniProtKB,A0A0B4ZZ86,A0A0B4ZZ86,NaN,GO:0004553,GO_REF:0000002,IEA,InterPro:IPR001137|InterPro:IPR013319,F,"Endo-1,4-beta-xylanase",NaN,protein,taxon:326423,20191214,InterPro,NaN,NaN
2,UniProtKB,A0A0B4ZZ86,A0A0B4ZZ86,NaN,GO:0005975,GO_REF:0000002,IEA,InterPro:IPR001137,P,"Endo-1,4-beta-xylanase",NaN,protein,taxon:326423,20191214,InterPro,NaN,NaN
3,UniProtKB,A0A0B4ZZ86,A0A0B4ZZ86,NaN,GO:0005975,GO_REF:0000038,IEA,UniProtKB-KW:KW-0119,P,"Endo-1,4-beta-xylanase",NaN,protein,taxon:326423,20191214,UniProt,NaN,NaN
4,UniProtKB,A0A0B4ZZ86,A0A0B4ZZ86,NaN,GO:0008152,GO_REF:0000038,IEA,UniProtKB-KW:KW-0326,P,"Endo-1,4-beta-xylanase",NaN,protein,taxon:326423,20191214,UniProt,NaN,NaN

Converted Geobacillus_kaustophilus_HTA426-235909.gaf to Geobacillus_kaustophilus_HTA426-235909.csv

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,UniProtKB,A0A386HYH7,COI,NaN,GO:0004129,GO_REF:0000002,IEA,InterPro:IPR000883|InterPro:IPR023616,F,Cytochrome c oxidase subunit 1,COI,protein,taxon:2359098,20191214,InterPro,NaN,NaN
1,UniProtKB,A0A386HYH7,COI,NaN,GO:0004129,GO_REF:0000003,IEA,EC:1.9.3.1,F,Cytochrome c oxidase subunit 1,COI,protein,taxon:2359098,20191214,UniProt,NaN,NaN
2,UniProtKB,A0A386HYH7,COI,NaN,GO:0005739,GO_REF:0000038,IEA,UniProtKB-KW:KW-0496,C,Cytochrome c oxidase subunit 1,COI,protein,taxon:2359098,20191214,UniProt,NaN,NaN
3,UniProtKB,A0A386HYH7,COI,NaN,GO:0005743,GO_REF:0000038,IEA,UniProtKB-KW:KW-0999,C,Cytochrome c oxidase subunit 1,COI,protein,taxon:2359098,20191214,UniProt,NaN,NaN
4,UniProtKB,A0A386HYH7,COI,NaN,GO:0005743,GO_REF:0000040,IEA,UniProtKB-SubCell:SL-0168,C,Cytochrome c oxidase subunit 1,COI,protein,taxon:2359098,20191214,UniProt,NaN,NaN

Converted Escherichia_coli_K-12_ecocyc_83333.gaf to Escherichia_coli_K-12_ecocyc_83333.csv

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,UniProtKB,P0A776,rppH,NaN,GO:0050779,PMID:18202662,IMP,NaN,P,NaN,NaN,gene,taxon:83333,20081017,EcoliWiki,NaN,NaN
1,UniProtKB,P0A776,rppH,NaN,GO:0034353,PMID:18202662,IDA,NaN,F,NaN,NaN,gene,taxon:83333,20081017,EcoliWiki,NaN,NaN
2,UniProtKB,P0A776,rppH,NaN,GO:0016818,PMID:18202662,IDA,NaN,F,NaN,NaN,gene,taxon:83333,20081017,EcoliWiki,NaN,NaN
3,UniProtKB,P37351,rpiB,NaN,GO:0004751,PMID:8576032,IDA,NaN,F,NaN,NaN,gene,taxon:83333,20081017,EcoliWiki,NaN,NaN
4,UniProtKB,P37351,rpiB,NaN,GO:0004751,PMID:8576032,IGI,EcoliWiki:rpiA,F,NaN,NaN,gene,taxon:83333,20081017,EcoliWiki,NaN,NaN

Converted Bacillus_licheniformis_ATCC_14580-279010.gaf to Bacillus_licheniformis_ATCC_14580-279010.csv

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,UniProtKB,A4VF87,BL07011,NaN,GO:0016020,GO_REF:0000038,IEA,UniProtKB-KW:KW-0472,C,Uncharacterized protein,BL07011,protein,taxon:279010,20191214,UniProt,NaN,NaN
1,UniProtKB,A4VF87,BL07011,NaN,GO:0016021,GO_REF:0000038,IEA,UniProtKB-KW:KW-0812,C,Uncharacterized protein,BL07011,protein,taxon:279010,20191214,UniProt,NaN,NaN
2,UniProtKB,A4VFE7,BL07067,NaN,GO:0016020,GO_REF:0000038,IEA,UniProtKB-KW:KW-0472,C,Uncharacterized protein,BL07067,protein,taxon:279010,20191214,UniProt,NaN,NaN
3,UniProtKB,A4VFE7,BL07067,NaN,GO:0016021,GO_REF:0000038,IEA,UniProtKB-KW:KW-0812,C,Uncharacterized protein,BL07067,protein,taxon:279010,20191214,UniProt,NaN,NaN
4,UniProtKB,A5A636,BL02379,NaN,GO:0016020,GO_REF:0000038,IEA,UniProtKB-KW:KW-0472,C,Uncharacterized protein,BL02379,protein,taxon:279010,20191214,UniProt,NaN,NaN

In [5]:
column_names = [
    "DB",
    "DB Object ID",
    "DB Object Symbol",
    "Qualifier",
    "GO ID",
    "DB:Reference",
    "Evidence Code",
    "With (or) From",
    "Aspect",
    "DB Object Name",
    "DB Object Synonym",
    "DB Object Type",
    "Taxon",
    "Date",
    "Assigned By",
    "Annotation Extension",
    "Gene Product Form ID",
]

all_dfs = []
for gaf_file in gaf_files:
    gaf_path = Path(input_files) / gaf_file
    temp_df = pd.read_csv(gaf_path, sep="\t", comment="!", header=None, dtype=str)
    temp_df.columns = column_names
    all_dfs.append(temp_df)

combined_df = pd.concat(all_dfs, ignore_index=True)
combined_csv_path = Path(input_files) / "combined_annotations.csv"
combined_df.to_csv(combined_csv_path, index=False)

print(f"Saved combined file to {combined_csv_path}")
display(combined_df.head())

Saved combined file to input_files/combined_annotations.csv

,DB,DB Object ID,DB Object Symbol,Qualifier,GO ID,DB:Reference,Evidence Code,With (or) From,Aspect,DB Object Name,DB Object Synonym,DB Object Type,Taxon,Date,Assigned By,Annotation Extension,Gene Product Form ID
0,UniProtKB,A4IJ84,dnaA,NaN,GO:0000166,GO_REF:0000037,IEA,UniProtKB-KW:KW-0547,F,Chromosomal replication initiator protein DnaA,dnaA|GTNG_0001,protein,taxon:420246,20191214,UniProt,NaN,NaN
1,UniProtKB,A4IJ84,dnaA,NaN,GO:0003677,GO_REF:0000002,IEA,InterPro:IPR001957|InterPro:IPR018312,F,Chromosomal replication initiator protein DnaA,dnaA|GTNG_0001,protein,taxon:420246,20191214,InterPro,NaN,NaN
2,UniProtKB,A4IJ84,dnaA,NaN,GO:0003677,GO_REF:0000037,IEA,UniProtKB-KW:KW-0238,F,Chromosomal replication initiator protein DnaA,dnaA|GTNG_0001,protein,taxon:420246,20191214,UniProt,NaN,NaN
3,UniProtKB,A4IJ84,dnaA,NaN,GO:0003688,GO_REF:0000002,IEA,InterPro:IPR001957|InterPro:IPR018312,F,Chromosomal replication initiator protein DnaA,dnaA|GTNG_0001,protein,taxon:420246,20191214,InterPro,NaN,NaN
4,UniProtKB,A4IJ84,dnaA,NaN,GO:0003688,GO_REF:0000104,IEA,UniRule:UR000084164,F,Chromosomal replication initiator protein DnaA,dnaA|GTNG_0001,protein,taxon:420246,20191214,UniProt,NaN,NaN

In [18]:
combined_df['Qualifier'].unique()

<StringArray>
[nan, 'Contributes_to']
Length: 2, dtype: str

In [16]:
len(combined_df)

1489